[package]
name = "fgr"
version = "0.1.0"
edition = "2018"
repository = "https://github.com/clinuxrulz/fgr4rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
